//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPWFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateTrack
    {
        public int Id { get; set; }
        public System.Guid InstanceId { get; set; }
        public System.DateTime DateOccured { get; set; }
        public string StateName { get; set; }
    }
}
