//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPWFUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStatu
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public System.Guid UniqueId { get; set; }
        public string DisplayName { get; set; }
    }
}
