//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPClientService.DBS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestAppsEntities : DbContext
    {
        public TestAppsEntities()
            : base("name=TestAppsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<WFAction> WFActions { get; set; }
        public DbSet<WFActionMovement> WFActionMovements { get; set; }
        public DbSet<WFCondition> WFConditions { get; set; }
        public DbSet<WFConditionMovement> WFConditionMovements { get; set; }
        public DbSet<WFMovement> WFMovements { get; set; }
        public DbSet<WorkflowInstance> WorkflowInstances { get; set; }
        public DbSet<WFStateTrack> WFStateTracks { get; set; }
    }
}
