//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPClientService.DBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCondition
    {
        public int Id { get; set; }
        public int CondType { get; set; }
        public string Condns { get; set; }
        public string FilePath { get; set; }
    }
}
