//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPClientService.DBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowInstance
    {
        public long WorkflowInstanceInternalId { get; set; }
        public System.Guid WorkflowInstanceId { get; set; }
        public System.Guid ContextGuid { get; set; }
        public Nullable<System.Guid> CallerInstanceId { get; set; }
        public string CallPath { get; set; }
        public Nullable<System.Guid> CallerContextGuid { get; set; }
        public Nullable<System.Guid> CallerParentContextGuid { get; set; }
        public int WorkflowTypeId { get; set; }
        public System.DateTime InitializedDateTime { get; set; }
        public System.DateTime DbInitializedDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.DateTime> DbEndDateTime { get; set; }
    }
}
